Deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,6 +14,14 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
+      # Clean up at the very start to ensure no stale worktrees
+      - name: Clean up existing worktree
+        run: |
+          git worktree prune
+          git worktree remove --force github-pages-deploy-action-temp-deployment-folder || true
+          rm -rf github-pages-deploy-action-temp-deployment-folder
+        if: always()
+
       - name: Checkout code
         uses: actions/checkout@v2
 
@@ -32,12 +40,12 @@ jobs:
       - name: Build
         run: pnpm run build
 
-      - name: Clean up existing worktree
-        # run: git worktree remove --force github-pages-deploy-action-temp-deployment-folder || true
-        run: |
-          git worktree remove --force github-pages-deploy-action-temp-deployment-folder || true
-          rm -rf github-pages-deploy-action-temp-deployment-folder
-        if: always()
+      # - name: Clean up existing worktree
+      #   # run: git worktree remove --force github-pages-deploy-action-temp-deployment-folder || true
+      #   run: |
+      #     git worktree remove --force github-pages-deploy-action-temp-deployment-folder || true
+      #     rm -rf github-pages-deploy-action-temp-deployment-folder
+      #   if: always()
 
       - name: Deploy to GitHub Pages
         uses: JamesIves/github-pages-deploy-action@4.1.5
